### ISSUE TITLE
Some images won't load with exiflibrary

### ISSUE THREAD

**Issue by devedse** [oozcitak/exiflibrary#60]
Hi @oozcitak ,

I tried loading the following image with exiftool but it fails on a specific tag not being found:
[Generated_0.zip](https://github.com/oozcitak/exiflibrary/files/3152542/Generated_0.zip)

This image was generated using the C# ImageSharp library.

I'm currently wondering wether the header is corrupt in the image itself, or the parsing is going wrong.

Some details of the exception:
![image](https://user-images.githubusercontent.com/2350015/57298749-3e786a00-70d3-11e9-94c4-ed76c46f8f8c.png)

**Comment by devedse** [comment]
I created the following sharable repository to try this issue out easily:
https://repl.it/@devedse/ErrorWhenLoadingJpgWithExif

**Comment by devedse** [comment]
I've now created a pull request to fix the issue, I'm not sure if this is the right way to fix it though. It seems that for some reason it finds the "First" header twice. To me it looks like the following code doesn't do the right check to see if it has even found the First header:

![image](https://user-images.githubusercontent.com/2350015/57489908-ccad4580-72b7-11e9-877d-7bfbe02a2000.png)

Shoudln't that code do some additional checks?

In the pull request I've simply added a check to see if that code has already been reached.

**Comment by SapientGuardian** [comment]
Jumping in here at @devedse 's request. I ran into a lot of stability issues with this library, and the fixes in the referenced PR are a subset of the fixes I made in attempt to fix them in my fork (which anyone is welcome to pillage) at https://github.com/SapientGuardian/exiflibrary . These did fix some problematic images, but not all of them.

While I certainly appreciate the effort that was put into this library, the amount of time I was spending patching it up for all of the crashes, loops, and memory explosions I ran into became untenable. I ended up abandoning my fork and writing my own exif library from scratch. Unfortunately, because this was done for and on the dime of my employer, I cannot share that project.

**Comment by oozcitak** [comment]
Thank you @SapientGuardian. I'll review and add your commits to the library.

**Comment by devedse** [comment]
@oozcitak @SapientGuardian , thanks guys :smile:. Really appreciated.

@oozcitak , I did already implement some of the changes from SapientGuardian in my repository. I'll leave it up to you on what else to add.

Maybe for the future I want to make an ExifLibrary based on the ExifParser used by ImageSharp. As that one might be somewhat more mature.

**Comment by devedse** [comment]
Might also be usefull to check out this guys commits, he has also done some fixes:
https://github.com/hgy59/exiflibrary/commit/b8edc8c60598f6033439bad8fa0bcb7239787e11
https://github.com/hgy59/exiflibrary/commit/2b9f3c0e792939e2dd00d242f42b92e96947c8ae

And this other person:
https://github.com/twsiyuan/exiflibrary/commit/2ecbf83b9c3de1e91339d1a280fd4fa6bee444eb

**Comment by oozcitak** [comment]
The referenced issue and other fixes suggested by @devedse and @SapientGuardian are now incorporated into the [latest release](https://www.nuget.org/packages/ExifLibNet/1.2.35).

**Comment by devedse** [comment]
Thanks, I'll retest
